package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    flutterEngine.getPlugins().add(new io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin());
    flutterEngine.getPlugins().add(new com.huawei.hms.flutter.ar.AREnginePlugin());
    flutterEngine.getPlugins().add(new com.huawei.hms.flutter.hmsavailability.HuaweiAvailabilityPlugin());
    flutterEngine.getPlugins().add(new com.huawei.hms.flutter.location.LocationPlugin());
    flutterEngine.getPlugins().add(new com.huawei.hms.flutter.map.HmsMap());
    flutterEngine.getPlugins().add(new com.huawei.hms.flutter.ml.HuaweiMlPlugin());
    flutterEngine.getPlugins().add(new com.huawei.hms.flutter.push.PushPlugin());
    flutterEngine.getPlugins().add(new com.huawei.hms.flutter.site.SitePlugin());
  }
}
